# Generated by Django 5.2.8 on 2025-11-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('leave', 'Leave'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('term_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=32)),
                ('carrier', models.CharField(max_length=128)),
                ('coverage_level', models.CharField(max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.employee')),
            ],
        ),
    ]
